name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Full-year commit calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_user: mendeseduarda

      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          plugin_user: mendeseduarda

      - name: GitHub projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          plugin_projects: yes
          plugin_projects_repositories: mendeseduarda/REPO_EXEMPLO
          plugin_projects_descriptions: yes
          plugin_user: mendeseduarda
